### ISSUE TITLE
About Environment installation

### ISSUE THREAD

**Issue by jianjun0407** [WinstonHuTiger/mamba_mae#1]
First of all, thank you for sharing.
![0](https://github.com/user-attachments/assets/04891506-37da-42fb-9a4e-e4cde8aa0d39)

When I run the command "pip install -e mamba2" in the build environment, I get the following error:
![1](https://github.com/user-attachments/assets/cbc995e2-ce69-4524-b575-db3264924a68)

![2](https://github.com/user-attachments/assets/a6426886-6e8a-402a-bd86-d82f0be11b68)

Do you have any good suggestions?

**Comment by WinstonHuTiger** [comment]
It seems that cuda ld library is missing on your machine and You have to install cuda toolkit on your machine.

**Comment by jianjun0407** [comment]
Yes, you're right.
