### ISSUE TITLE
Genetic_and_Histological_labels.xlsx

### ISSUE THREAD

**Issue by jianjun0407** [WinstonHuTiger/mamba_mae#3]
Can you upload a Genetic_and_Histological_labels.xlsx file as an example? thank you~
like this?
![3333](https://github.com/user-attachments/assets/676d1a93-e934-4f87-964d-7916984b6fae)

**Comment by WinstonHuTiger** [comment]
Let me ask Bran if I can share with you, since he did all the preprocessing work.

**Comment by WinstonHuTiger** [comment]
> Let me ask Bran if I can share with you, since he did all the preprocessing work.

The file is provided [here](assets/Genetic_and_Histological_labels.xlsx).
